### PR TITLE
added own serviceaccount for all components

### PR DESCRIPTION
**Pull request by ksandermann**
# Added own serviceaccount "neuvector" for all components

In cases where Neuvector will not be deployed in its own namespace, it is not advisable to use the default serviceaccount for the namespace and give it such high rights.

Any feedback welcome :)

### CODE REVIEW

**Comment by becitsthere** [comment]
1. Because the helm chart is also used in OpenShift, for backward compatibility, it is suggested to add both serviceAccount and serviceAccountName
```
  spec:
      serviceAccount: neuvector
      serviceAccountName: neuvector
```

2. automountServiceAccountToken is not necessary as the default value is true

3. Also need to change the following line in the README.md
`$ oc -n neuvector adm policy add-scc-to-user privileged -z default`

**Comment by ksandermann** [comment]
@becitsthere - Thanks for the feedback - done :)

**Comment by ksandermann** [comment]
I think there is an issue in the linting pipeline with the monitoring chart - Monitoring Chart shouldn't need to be bumped when sth on the core chart is changed right?

**Comment by becitsthere** [comment]
Monitor chart's issue should be fixed now.

**Comment by ksandermann** [comment]
@becitsthere - merged upstream master and bumped core chart version, monitor version bump issue in the pipeline still persists

**Comment by becitsthere** [comment]
The change has been incorporated into https://github.com/neuvector/neuvector-helm/commit/a0c4f1d4338dbe829bf081970d4b90ea6e3c1344.

To maintain backward compatibility, the "serviceAccount" parameter is added into values.yaml. You can change it to the one you plan to use.

I will close this PR. Thanks for your help.

**Pull request closed without merging**
