### PR TITLE
Allows specifying configuration files in a secret.

### PR DESCRIPTION
**Pull request by marcostvz**
fixes: https://github.com/neuvector/neuvector-helm/issues/119

As configmap included sensitive information (license, user passwords, OIDC settings...) we are adding the possiblity to configure the init files into a Secret using `controller.secret.data`.

This setting uses mapped values instead of multi-line strings, allowing single setting replacement (useful to define defaults).

### CODE REVIEW

**Comment by marcostvz** [comment]
If accepted, requires to update https://docs.neuvector.com/deploying/production/configmap, as now we use a secret.

**Comment by marcostvz** [comment]
@becitsthere I am not sure what's the contribution process here, but you seem to be the most active reviewer in the last months. Could you please take a look? Thanks! :)

**Comment by marcostvz** [comment]
Hello @jorn-k, is there any chance you could take a look to this MR? Thank you so much in advance!

**Comment by becitsthere** [comment]
This is a very good patch. Several users have requested to use secret to store the sensitive data. There are two concerns though,
1. This is a breaking change. We need to backward compatible.
2. Not all variables need to be stored in secrets, such as web hook or proxy settings.

**Comment by marcostvz** [comment]
Hi @becitsthere, I reworked the PR to allow both configmap and secret being used, while not breaking the existing format.

I hope you do not mind the format of specifying the data within secret section differing from the configmap section (uses yaml instead of multi-line strings). But that allows us to reuse default values which is great.

**Comment by becitsthere** [comment]
Looks good. A few changes need to make, for example, updating README file. I will do that after merge.

**Pull request merged**
