### PR TITLE
Updated for internal certificates

### PR DESCRIPTION
**Pull request by clemenko**
Updated the chart to handle internal certificate creation.

### CODE REVIEW

**Comment by garyduan** [comment]
The structure looks good. My concern is these settings don't convey the requirement that the certificated need to be all same globally, among controllers, enforcers and scanners. They need to be able to validate each other.

**Comment by clemenko** [comment]
> 

Interesting. I was able to get everything up and running with individual certificates. In theory if it is the same CA would they not still be able to authenticate each other? Besides I thought the Controller is the hub and scanner, enforcer and manager are the spokes. Is there communication between the spokes?

**Comment by garyduan** [comment]
That is true. As long as certs can validate each other, globally, it is fine. Controllers and enforcers form a mesh.

**Comment by clemenko** [comment]
So can we merge it?

**Comment by garyduan** [comment]
I think the current settings make people think each component can have their own set of certs independently. Is there a better way to convey the requirement of "globalness"?

**Comment by clemenko** [comment]
Since the helm chart does not have clear documentation we can possible add it to the values.yaml?

**Pull request merged**
