### PR TITLE
integrate ConfigMap into chart

### PR DESCRIPTION
**Pull request by timwebster9**

### CODE REVIEW

**Comment by asengqi** [comment]
To make sure configmap will be loaded before the controller, we prefer creating configmap from files first.

**Comment by timwebster9** [comment]
> To make sure configmap will be loaded before the controller, we prefer creating configmap from files first.

Do you see problems with this?

How about I make the volume **_not_** optional if `configmap.enabled` is true?  Then in theory the controller pod will block until the ConfigMap is available?

https://github.com/neuvector/neuvector-helm/blob/a364e05cc6c30ab711c40e8801f539dbd47336be/templates/controller-deployment.yaml#L112

I will test this on my end

**Comment by timwebster9** [comment]
@asengqi my suggestion works as expected.  If the volume is mandatory the pod won't start until the ConfigMap has been created.

I've pushed a commit to make the volume mandatory if `configmap.enabled` is true.

Ideally we wouldn't mix Helm and regular manifests, and k8s and Helm can manage this dependency themselves.  Also, when using some automation tools (we use Weave Flux), then the order of resource application is not guaranteed, so it's better to let k8s and Helm manage the dependencies.

**Comment by asengqi** [comment]
Thank you for this great suggestion. I have reported to our engineers.

**Pull request merged**
